name: musix
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dart_des: ^1.0.2
  flutter:
    sdk: flutter
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.2.1
  just_audio: ^0.9.39
  just_audio_windows: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
